### ISSUE TITLE
Landing page {profiles}

### ISSUE THREAD

**Issue by monteirocamis** [monteirocamis/trocatexproject#2]
Do a simple one-page like landing page 

The most important part is to have an area for profiles with:

-     foto area
-     name
-     -city
-     type of lefttovers
-     small image of telephone with number in front
-     -image with link going to facebook

You can use Placeholder images and lorem ipsum ;)

We can use Html,css, JS, React, and other language you want to suggest for us ;)

**Comment by dbrahmania** [comment]
HI @monteirocamis, I would like to contribute on the front-end. I have experience with React. I can take up this issue.

**Comment by monteirocamis** [comment]
Hii @deepak-brahmania , perfect! I use react, so it's going to be good=)
I have made a simple frame of the landing page   that you can inspire from that.
Would you like to start from zero or want me start and then you go forward?

![wireframe trocatex](https://user-images.githubusercontent.com/26682838/47246739-fcf1cd00-d3d5-11e8-834b-a149887be61a.png)

**Comment by monteirocamis** [comment]
@deepak-brahmania  ah! would you like me to change the language for english?We can start in english and then more forward I make the changes ;)

**Comment by dbrahmania** [comment]
@monteirocamis Yeah It will be helpful if its in English. Thanks :)
I can start from Zero.

**Comment by monteirocamis** [comment]
heey @deepak-brahmania Very good job !!! I started to continue the project making some small changes just to see your code hehe 
Would you like to keep maintaining the website with us? 
If you agree, let's check the other new issues that I will create for us ;)
Thank you very much!
