### ISSUE TITLE
Logo TrocaTex 

### ISSUE THREAD

**Issue by monteirocamis** [monteirocamis/trocatexproject#3]
We need a logo  for our project that shows change, movement , eco and modern stuff .
Insert your idea on  _Imgs_ folder

**Comment by richardbmx** [comment]
@monteirocamis  Hi, my name is Richard. I'm a graphic designer and I love making contributions for open source projects. I see that they want a new logo for your application. If you wish, I can do it for you without any problem ... I can present some modern ideas that would improve the appearance and image of your project

**Comment by monteirocamis** [comment]
Heey @richardbmx , thank you for your message,I would be greatful !
I am starting to insert informations here , tell me what you need for make it and I publish here =)  keep in touch

**Comment by richardbmx** [comment]
@monteirocamis  I would like to know what the project is about what its functions are so you can make a logo that represents your project at first sight

**Comment by monteirocamis** [comment]
@richardbmx Sure.
The project now is a simple website that people can see brands, ateliers and people wich have leftovers for donate/share with others.
So, the website will be like a window with cards of contents containing the contact information and fabrics leftover information for people get in touch and talk each other for it

Inside the website: 
You go inside the website > search for fabric that you need, look for profile-cards-section, with pictures and cities of people that have leftovers > you take notes of telefones or e-mail adresses for present yourself and schedule the exchange

Outside of website: 
you start talking to the person by telephone, whatsapp ou e-mail> meet the person in a place outside of the website and take the leftovers :)

I'm doing the frames for show you how is the first version of the website ;)

**Comment by monteirocamis** [comment]
![wireframe trocatex](https://user-images.githubusercontent.com/26682838/47195903-63261380-d334-11e8-91d3-bca6b509aaf6.png)
@richardbmx

**Comment by richardbmx** [comment]
@monteirocamis  Perfect knowing this I will start working on a logo

**Comment by richardbmx** [comment]
@monteirocamis  I present this proposal based on a scissors giving the impression of cutting a fabric and the colors of the top is to identify different colors of fabric, I hope you like it if you want some change you just have to ask

![logo116](https://user-images.githubusercontent.com/35604837/47271110-211eec80-d543-11e8-8c13-a7268da5404d.png)

**Comment by richardbmx** [comment]
@monteirocamis  Hello, I would like to know if you have seen the proposal?

**Comment by monteirocamis** [comment]
heey @richardbmx , sorry.Crazy times here in Brazil, So, I prefer the first option and the blue one  =)

**Comment by richardbmx** [comment]
@monteirocamis  perfect do not worry ... if you do not want any change you can generate all the files so you can use the logo and generate a Pull requests with the incorporation of the logo

**Comment by richardbmx** [comment]
@monteirocamis  Here you can find a Google folder with all the necessary files to use the logo, find different variations in different formats and also open a file that grants all the rights for free use.

[Google Drive](https://drive.google.com/open?id=1Ydx8yGDPPWRbbtyM8qWbaBhEWsb09cUC)

**Comment by richardbmx** [comment]
I created a Pull requests by adding the logotypo
